#spring.datasource.url=databaseUrl
#spring.datasource.username=yourName
#spring.datasource.password=yourPassword
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
