spring.datasource.url=jdbc:postgresql://dpg-d09sp4h5pdvs73br6j8g-a.oregon-postgres.render.com/consultalegal
spring.datasource.username=consultalegal
spring.datasource.password=MHRsg6R6Z9ngp88e8GDiWZv9YasRs7Aw

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect